GET http://localhost:8000/api/user

###

GET http://localhost:8000/api/user/62a6ac4f206eed8f62acd541

###

GET http://localhost:8000/api/blog/62a793c2d06ad54e01aa0be4

###

POST http://localhost:8000/api/user/signup
Content-Type: application/json

{
    "name": "Raj",
    "email": "Raj6400@gmail.com",
    "password": "Mongoose"
}

###
DELETE http://localhost:8000/api/user/62a6060e6d1822d5d02abfc3

###

PATCH http://localhost:8000/api/user/62a6060e6d1822d5d02abfc3
Content-Type: application/json

{
    "name": "Hrithik"
}